### ISSUE TITLE
Network Error: Maximum Retries Exceeded With URL

### ISSUE THREAD

**Issue by ryhiltabrand** [internetarchive/pdf_trio#1]
I have followed the README, specifically Quickstart with docker compose. This has set up both the TensorFlow flow back-end daemons and the local API service using docker-compose up. However when I run the example curl command and the curl command with my own PDFs but I always receive the same error that ends with:

```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: /v1/models/image_model (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f82d3d28a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

I have attached the full error message in a text file ([error.txt](https://github.com/internetarchive/pdf_trio/files/6088445/error.txt)) if that gives you any context clue to what the issue is.

If you could give me any more documentation on how this works or how to fix this issue it would be helpful.

**Comment by bnewbold** [comment]
Hi @ryhiltabrand, glad to hear you are giving it a try, and sorry to hear you are having trouble.

I just gave the docker-compose setup a try on my laptop, which is running:

```
bnewbold@orithena$ head -n1 /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)
bnewbold@orithena$ docker --version
Docker version 20.10.2, build 2291f61
bnewbold@orithena$ docker-compose --version
docker-compose version 1.27.4, build 40524192
```
and I am getting the same error as you.

**Comment by bnewbold** [comment]
I just pushed a change to how the API service talks to the tfserving service in the docker-compose configuration. Could you pull and give that a try?

**Comment by ryhiltabrand** [comment]
I just pulled and I am getting results now. Thanks.
